name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux-gcc:
      name: Linux GCC
      runs-on: ubuntu-22.04
      env:
          CC: gcc-12
          CXX: g++-12
      steps:
          - uses: actions/checkout@v3
          - name: dependency
            run: |
                sudo apt-get update
                sudo apt-get install -y ninja-build g++-12 build-essential libstdc++-12-dev libgtest-dev
          - run: make
          - run: make test

